[package]
name = "mnist_trainer"
version = "0.1.0"
authors = ["Louis de Wardt <contact@louis.dewardt.uk>"]

[dependencies]
network = { path = "../network" }
mnist = "0.4.0"
rand = "0.6"
serde_json = "1.0"
clap = {version = "2.33", features = ["yaml"]}
